name: Dendron

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v2


    - name: Clean cache
      run: npm cache clean --force
    - name: rm node modules
      run: rm -rf node_modules
    - name: Install npm dependencies
      run: npm install
      
   # - name: Install latest dendron-cli
   #   run: npm install @dendronhq/dendron-cli@latest
    
   # - name: Install latest dendron-11ty
   #   run: npm install @dendronhq/dendron-11ty@latest

    - name: Build pod
      run: npm run dendron-cli -- buildSiteV2 --wsRoot .  --stage prod

    - name: Deploy site
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: pages
        publish_dir: docs/
        force_orphan: true
